---
- name: INSTALL_YARN | Add an apt gpg key from yarnpkg
  apt_key:
    url: "{{ nodejs_yarn_gpg_key_url }}"
    state: present

- name: INSTALL_YARN | Add yarn repository
  apt_repository:
    repo: "{{ nodejs_yarn_repo_url }}"
    state: present
    filename: yarn.list

- name: INSTALL_YARN | install yarn
  apt:
    name: "yarn={{ nodejs_yarn_version }}"
    state: present
    update_cache: true
    install_recommends: false
