---
- name: Install nodejs
  import_tasks: install_nodejs.yml
  when: nodejs_current_major_version != (nodejs_version | string)
  tags: install

- name: Install yarn
  import_tasks: install_yarn.yml
  when: nodejs_yarn_enabled
  tags: install
